from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_desc = fh.read()

setup(
    name = "stream-analyser",
    version = "v0.1.0",
    author = "emso-c",
    author_email = "emsoc192@gmail.com",
    description = ("Live stream analyser"),
    keywords = ['youtube', 'live', 'stream', 'chat', 'highlight', 'analyser'],
    url = "https://github.com/emso-c/stream-analyser",
    long_description=long_desc,
    long_description_content_type="text/markdown",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: Microsoft :: Windows :: Windows 10",
        "Environment :: Console",
        "Natural Language :: English",
        "Programming Language :: Python",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Information Analysis",
    ],
    packages = find_packages("streamanalyser"),
    package_dir={"": "streamanalyser"},
    python_requires=">=3.9",
    include_package_data=True,
    install_requires=[
        'build>=0.5.1',
        'certifi>=2020.12.5',
        'chardet>=4.0.0',
        'chat-downloader>=0.0.8',
        'colorama>=0.4.4',
        'colorlog>=5.0.1',
        'cycler>=0.10.0',
        'DateTime>=4.3',
        'docstring-parser>=0.8.1',
        'idna>=2.10',
        'isodate>=0.6.0',
        'kiwisolver>=1.3.1',
        'matplotlib>=3.4.2',
        'numpy>=1.20.3',
        'packaging>=21.0',
        'pep517>=0.10.0',
        'Pillow>=8.2.0',
        'pyparsing>=2.4.7',
        'python-dateutil>=2.8.1',
        'pytz>=2021.1',
        'PyYAML>=5.4.1',
        'regex>=2021.4.4',
        'requests>=2.25.1',
        'six>=1.16.0',
        'toml>=0.10.2',
        'urllib3>=1.26.5',
        'zope.interface>=5.4.0',
    ]
)
