path-to:
  cache: src\cache
  metadata: src\metadata
  contexts: src\context.json
  default-export: C:\Stream analyser\Exports
  logs: src\logs
  thumbnails: src\thumbnails
  fonts: src\fonts
intensity:
  levels: [low, medium, high, very high, ultra high]
  constants: [0, 0.5, 1, 1.5, 2.5]
  colors: [YELLOW, CYAN, BLUE, RED, MAGENTA]
interval: 30
keyword-limit: 4
keyword-filters: ['of', 'a', 'the', 'i', 'be', 'am', 'and', 'it', 'is', "isnt", 'was', 'you', 'can', "can't"]
cache-size: 40
log-duration-days: 7
min-hl-duration: 10
